task/urls.py
from django.urls import path

from task.views import (
    index,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    change_status,
    TagsListView,
    TagsUpdateView,
    TagsCreateView,
    TagsDeleteView,
)

urlpatterns = [
    path("", index, name="main-page"),
    path("task/create/", TaskCreateView.as_view(), name="task-create"),
    path("task/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("task/<int:pk>/change/", change_status, name="task-change-status"),
    path("tags/", TagsListView.as_view(), name="tags-list"),
    path("tags/create/", TagsCreateView.as_view(), name="tags-create"),
    path("tags/<int:pk>/update/", TagsUpdateView.as_view(), name="tags-update"),
    path("tags/<int:pk>/delete/", TagsDeleteView.as_view(), name="tags-delete"),
]

app_name = "task"

task_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("task.urls", namespace="task")),
]

task/models.py
from django.db import models
from django.utils import timezone


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=255)
    datetime = models.DateTimeField(auto_now_add=True)
    deadline_datetime = models.DateTimeField(blank=True, null=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.content

    class Meta:
        ordering = ["is_done", "-datetime"]
        verbose_name = "task"
        verbose_name_plural = "tasks"

task/forms.py
from django import forms

from task.models import Task, Tag


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple(),
        label="Tags"
    )

    class Meta:
        model = Task
        fields = "__all__"


class TagForm(forms.ModelForm):

    class Meta:
        model = Tag
        fields = "__all__"

task/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.http import HttpResponseRedirect
from task.forms import TaskForm, TagForm
from task.models import Task, Tag
from django.urls import reverse_lazy


def index(request):
    tasks = Task.objects.all()

    context = {"tasks": tasks}

    return render(request, "task/index.html", context=context)


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("task:main-page")
    template_name = "task/task_form.html"


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("task:main-page")
    template_name = "task/task_form.html"


class TaskDeleteView(generic.DeleteView):
    model = Task
    context_object_name = "task"
    template_name = "task/task_confirm_delete.html"
    success_url = reverse_lazy("task:main-page")


def change_status(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.is_done = not task.is_done
    task.save()

    return redirect("task:main-page")


class TagsListView(generic.ListView):
    model = Tag
    template_name = "task/tag_list.html"


class TagsCreateView(generic.CreateView):
    model = Tag
    form_class = TagForm
    template_name = "task/tag_form.html"
    success_url = reverse_lazy("task:tags-list")


class TagsUpdateView(generic.UpdateView):
    model = Tag
    form_class = TagForm
    template_name = "task/tag_form.html"
    success_url = reverse_lazy("task:tags-list")


class TagsDeleteView(generic.DeleteView):
    model = Tag
    context_object_name = "tag"
    template_name = "task/tag_confirm_delete.html"
    success_url = reverse_lazy("task:tags-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>To Do List</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
{#    {% load static %}#}
{#    <link rel="stylesheet" href="{% static 'css/styles.css' %}">#}
</head>
<body>
  <div class="container-fluid">
      <div class="row">
          <div class="col-sm-2">
              {% block sidebar %}
                  {% include "includes/sidebar.html" %}
              {% endblock %}
          </div>
          <div class="col-sm-10 ">
              {% block content %}{% endblock %}
          </div>
      </div>
  </div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'task:main-page' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'task:tags-list' %}">Tags</a></li>
</ul>

templates/task/index.html
{% extends "base.html" %}
{% block content %}
  <div class="d-flex justify-content-between align-items-center">
    <h1>TODO List:</h1>
    <a href="{% url 'task:task-create' %}" class="btn btn-primary">Create Task</a>
  </div>
  <br>
  {% if tasks %}
    {% for task in tasks %}
      <h3>{{ task.content }}
      {% if task.is_done %}
        <span style="color: green">Done</span>
        <a class="btn btn-secondary link-to-page" href="{% url 'task:task-change-status' pk=task.pk %}">Undo</a>
      {% else %}
        <span style="color: red">Not done</span>
        <a class="btn btn-success link-to-page" href="{% url 'task:task-change-status' pk=task.pk %}">Complete</a>
      {% endif %}
      </h3>
      <p>Created at: {{ task.datetime }}{% if task.deadline_datetime %} <span style="color: coral">Deadline:{{ task.deadline_datetime }}
      </span>{% endif %}</p>
      <p>Tags:
      {% for tag in task.tags.all %}{{ tag.name }} {% endfor %}
      <a href="{% url 'task:task-update' pk=task.id %}" style="text-decoration: none">Update</a>
      <a href="{% url 'task:task-delete' pk=task.id %}" style="text-decoration: none">Delete</a>
      </p>
      <hr>
    {% endfor %}
  {% else %}
    <p>There are no tasks</p>
  {% endif %}
{% endblock %}

templates/task/tag_confirm_delete.html
{% extends "base.html" %}
{% block content %}
  <form action="" method="post">
  {% csrf_token %}
  <p>Are you sure you want to delete this tag({{ tag }})?</p>
  <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/task/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <div class="container py-5">
    <h1>{{ object|yesno:"Update,Create" }} Tag</h1>
    <form action="" method="post" class="my-form">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-primary btn-block">Submit</button>
    </form>
  </div>
{% endblock %}

templates/task/tag_list.html
{% extends "base.html" %}
{% block content %}
  <div class="d-flex justify-content-between align-items-center">
    <h1>Tags:</h1>
    <a href="{% url "task:tags-create" %}" class="btn btn-primary">Create Tag</a>
  </div>
  {% if tag_list %}
     <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for tag in tag_list %}
        <tr>
          <td>
              {{ tag.name }}
          </td>
          <td>
            <a class="btn btn-secondary" href="{% url 'task:tags-update' tag.pk %}">Update</a>
          </td>
          <td>
            <a class="btn btn-secondary" href="{% url 'task:tags-delete' tag.pk %}">Delete</a>
          </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
  {% endif %}
{% endblock %}

templates/task/task_confirm_delete.html
{% extends "base.html" %}
{% block content %}
  <form action="" method="post">
  {% csrf_token %}
  <p>Are you sure you want to delete this task({{ task }})?</p>
  <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/task/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <div class="container py-5">
    <h1>{{ object|yesno:"Update,Create" }} Task</h1>
    <form action="" method="post" class="my-form">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-primary btn-block">Submit</button>
    </form>
  </div>
{% endblock %}